ci: améliorations diverses (Terraform & Scalingo) (#1511)
* ci: arrêter le déploiement terraform

* ci: ne déclencher le terraform que lorsque des fichiers Terraform sont modifiés

* ci: ajout du déploiement Scalingo dans le workflow

* chore(ci): renommage des éléments de MEP Terraform pour être prêt à merger

diff --git a/.github/workflows/terraform-template.yml b/.github/workflows/terraform-template.yml
--- a/.github/workflows/terraform-template.yml
+++ b/.github/workflows/terraform-template.yml
@@ -68,6 +68,25 @@ jobs:
         run: |
           npm install -g envsub
           envsub --syntax dollar-curly --protect .env.scalingo .env
+      
+      - name: Vérifier que toutes les variables d'environnement sont définies
+        run: |
+          NUMBER=0
+          ENV_FILE=".env"
+          REGEX='^([a-zA-Z_]+[a-zA-Z0-9_]*)=\$\{(.*)\}$'
+
+          while read line
+          do
+            if [[ "$line" =~ $REGEX ]]; then
+              echo "ERROR: value is missing for the env ${BASH_REMATCH[2]}"
+              ((NUMBER++))
+            fi
+          done < "$ENV_FILE"
+
+          if [[ $NUMBER -gt 0 ]]; then
+            echo "Il y a $NUMBER variables d'environnement non définies, nous ne pouvons pas continuer le déploiement"
+            exit 1
+          fi
 
       - name: Vérifier le format et le style du code Terraform
         if: ${{ inputs.lint == true }}
