ci: arrêter le déploiement terraform

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -68,6 +68,22 @@ jobs:
         run: |
           npm install -g envsub
           envsub --syntax dollar-curly --protect .env.scalingo .env
+      
+      - name: Vérifier que toutes les variables d'environnement sont définies
+        run: |
+          NUMBER=0
+          REGEX_NON_DEFINED_ENVS='^([a-zA-Z_]+[a-zA-Z0-9_]*)=\${(.+)}$'
+          foreach line (`cat .env.scalingo`)
+            if [[ $line =~ ${~REGEX_NON_DEFINED_ENVS} ]]; then
+              echo "a value is missing for the env $match[1]"
+              let "NUMBER+=1"
+            fi
+          end
+
+          if [[ $NUMBER -gt 0 ]]; then
+            echo "Il y a $NUMBER variables d'environnement non définies, nous ne pouvons pas continuer le déploiement"
+            exit 1
+          fi
 
       - name: Vérifier le format et le style du code Terraform
         if: ${{ inputs.lint == true }}
